#!/bin/zsh

if [[ $# -lt 2 ]]; then
    echo 'usage: mkalias ALIAS COMMAND...' >&2
    return 2
else
    name="$1"
    shift
    f=$ZSH_CONFIG_DIR/aliases/"$name"
    echo "$*" > "$f"
    . $ZSH_LIB_DIR/common.zsh
    read-alias-file "$f"
    echo "$name='$*'"
    unset name f
fi
