#!/bin/zsh

for f in $ZSH_CONFIG_DIR/plugins/*(/); do
    echo "Updating $f:t..."
    if ! git -C "$f" pull 2>/dev/null; then
        # Fallback for old git versions without -C flag.
        (cd "$f"; git pull)
    fi
done

unset f
