#!/bin/zsh

TOOLBOX_DOCKERFILE="${TOOLBOX_DOCKERFILE:-Dockerfile.toolbox}"

dir_name() { echo "${PWD##*/}" }
image_name() { echo "$(dir_name)"-toolbox }
container_name() { echo "$(image_name)"-latest }

create() {
    i="$(image_name)"
    cmd=(toolbox create)
    if [[ -n "$1" ]]; then
        cmd+=(--image "$1")
    elif podman image exists "$i"; then
        cmd+=(--image "$i":latest)
    elif [[ -e "$TOOLBOX_DOCKERFILE" ]]; then
        podman build -f "$TOOLBOX_DOCKERFILE" -t "$i" . \
            && cmd+=(--image "$i":latest)
    fi
    ${cmd[@]}
}

container() {
    c="$(container_name)"
    case "$1" in
        rm|stop)
            podman ps | grep -q "$c" && podman container stop "$c" ;&
        rm)
            podman container exists "$c" && podman container rm "$c"
    esac
}

rm_image() {
    i="$(image_name)"
    container rm
    podman image exists "$i" && podman image rm "$i"
}

if [[ $# -eq 0 ]]; then
    c="$(container_name)"
    podman container exists "$c" || create
    toolbox enter --container "$c"
    return $?
fi

case "$1" in
    create) shift; create "$1" ;;
    recreate) container rm; create ;;
    rebuild) rm_image; create ;;
    stop|rm) container "$1" ;;
    rmi) rm_image ;;
    *) toolbox "$@"
esac
