#!/bin/zsh

TOOLBOX_DOCKERFILE="${TOOLBOX_DOCKERFILE:-Dockerfile.toolbox}"

dir_name() { echo "${PWD##*/}" }
image_name() { echo "$(dir_name)"-toolbox }
container_name() { echo "$(image_name)"-latest }

img_exists() {
    podman image exists "$1"
}

build() {
    f="${2-$TOOLBOX_DOCKERFILE}"
    if [[ -e "$f" ]]; then
        podman build -f "$f" -t "${1-$(image_name)}" .
    else
        echo "$f does not exist" >&2
        return 1
    fi
}

create() {
    i="$(image_name)"
    cmd=(toolbox create)
    if [[ -n "$1" ]]; then
        cmd+=(--image "$1")
    elif img_exists "$i" || build "$i"; then
        cmd+=(--image "$i":latest)
    else
        return 1
    fi
    ${cmd[@]}
}

container() {
    c="$(container_name)"
    if [[ "$1" == rm || "$1" == stop ]]; then
        podman ps | grep -q "$c" && podman container stop "$c"
    fi
    if [[ "$1" == rm ]]; then
        podman container exists "$c" && podman container rm "$c"
    fi
}

rm_image() {
    i="$(image_name)"
    container rm
    img_exists "$i" && podman image rm "$i"
}

rpkg_local() {
    i="$(image_name)"
    img_exists "$i" || build "$i" || return 1

    d="$(dir_name)"
    dir="$(find . -maxdepth 2 -name "$d".spec.rpkg -printf '%h\n' -quit)"
    [[ -n "$dir" ]] || return 1

    out="$(mktemp --tmpdir -d "$d"-XXX)"

    podman run --rm -v "$out":/out:Z -v "$PWD":/rpkg:Z -w /rpkg \
        "$(image_name)" rpkg --path "$dir" local --outdir /out

    [[ $? -eq 0 ]] || return $?

    if [[ $1 == 'install' ]]; then
        dnf install "$(find $out -regextype posix-extended \
            -regex "$out/($(uname -m)|noarch)/$d"'-[0-9\.].*\.rpm')"
    fi
}

if [[ $# -eq 0 ]]; then
    c="$(container_name)"
    echo 'Entering toolbox...'
    podman container exists "$c" || create && toolbox enter --container "$c"
    return $?
fi

case "$1" in
    create) shift; create "$1" ;;
    recreate) container rm; create ;;
    build) shift; [[ $# -gt 0 ]] && build "$@" ;;
    rebuild) container rm; build; create ;;
    stop|rm) container "$1" ;;
    rmi) rm_image ;;
    rpkg) rpkg_local ;;
    rpkg-install) rpkg_local install ;;
    *) toolbox "$@"
esac
